/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfRouteImport } from './routes/perf'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAdvancedRouteImport } from './routes/settings/advanced'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsEditorRouteImport } from './routes/settings/editor'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsHotkeysRouteImport } from './routes/settings/hotkeys'
import { Route as SettingsSearchRouteImport } from './routes/settings/search'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings/workspace'
import { Route as VaultVaultIdRouteImport } from './routes/vault/$vaultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfRoute = PerfRouteImport.update({
  id: '/perf',
  path: '/perf',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsEditorRoute = SettingsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsHotkeysRoute = SettingsHotkeysRouteImport.update({
  id: '/hotkeys',
  path: '/hotkeys',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSearchRoute = SettingsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const VaultVaultIdRoute = VaultVaultIdRouteImport.update({
  id: '/vault/$vaultId',
  path: '/vault/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/perf': typeof PerfRoute
  '/welcome': typeof WelcomeRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/search': typeof SettingsSearchRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perf': typeof PerfRoute
  '/welcome': typeof WelcomeRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/search': typeof SettingsSearchRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/perf': typeof PerfRoute
  '/welcome': typeof WelcomeRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/search': typeof SettingsSearchRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/vault/$vaultId': typeof VaultVaultIdRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/perf'
    | '/welcome'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/editor'
    | '/settings/files'
    | '/settings/hotkeys'
    | '/settings/search'
    | '/settings/workspace'
    | '/vault/$vaultId'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/perf'
    | '/welcome'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/editor'
    | '/settings/files'
    | '/settings/hotkeys'
    | '/settings/search'
    | '/settings/workspace'
    | '/vault/$vaultId'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/perf'
    | '/welcome'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/editor'
    | '/settings/files'
    | '/settings/hotkeys'
    | '/settings/search'
    | '/settings/workspace'
    | '/vault/$vaultId'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  PerfRoute: typeof PerfRoute
  WelcomeRoute: typeof WelcomeRoute
  VaultVaultIdRoute: typeof VaultVaultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perf': {
      id: '/perf'
      path: '/perf'
      fullPath: '/perf'
      preLoaderRoute: typeof PerfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/editor': {
      id: '/settings/editor'
      path: '/editor'
      fullPath: '/settings/editor'
      preLoaderRoute: typeof SettingsEditorRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/hotkeys': {
      id: '/settings/hotkeys'
      path: '/hotkeys'
      fullPath: '/settings/hotkeys'
      preLoaderRoute: typeof SettingsHotkeysRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/search': {
      id: '/settings/search'
      path: '/search'
      fullPath: '/settings/search'
      preLoaderRoute: typeof SettingsSearchRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/vault/$vaultId': {
      id: '/vault/$vaultId'
      path: '/vault/$vaultId'
      fullPath: '/vault/$vaultId'
      preLoaderRoute: typeof VaultVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsEditorRoute: typeof SettingsEditorRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsHotkeysRoute: typeof SettingsHotkeysRoute
  SettingsSearchRoute: typeof SettingsSearchRoute
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsEditorRoute: SettingsEditorRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsHotkeysRoute: SettingsHotkeysRoute,
  SettingsSearchRoute: SettingsSearchRoute,
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  PerfRoute: PerfRoute,
  WelcomeRoute: WelcomeRoute,
  VaultVaultIdRoute: VaultVaultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
